// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // assert non-null since dotenv/config is loaded and DATABASE_URL should be defined
    url: process.env["DATABASE_URL"]!,
  },
});
